# dont need this anymore, but useful for test deployment
# requires separate service providing postgres database
version: '3'

services:
  pygeoapi:
    build: .
    container_name: reference-geoconnex-us
    ports:
      - 5000:80
    env_file:
      - .env

  database:
    container_name: database
    image: postgis/postgis:14-3.2-alpine
    env_file:
      - .env

  hydrodump:
    container_name: hydrodump
    image: ghcr.io/cgs-earth/hydrodump-action:latest
    command: ["hydrodump", "run"]
    env_file:
      - .env
