# dont need this anymore, but useful for test deployment
# requires separate service providing postgres database
version: '3'

services:
  reference-geoconnex-us:
    build: pygeoapi
    container_name: reference-geoconnex-us
    ports:
      - "5000:80"
    environment:
      - PYGEOAPI_URL=http://localhost:5000
      - POSTGRES_HOST=database
      - POSTGRES_DB=reference
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=changeMe
    restart: always

  database:
    container_name: database
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_DB=reference
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=changeMe
    volumes:
      - ./reference.sql.gz:/docker-entrypoint-initdb.d/reference.sql.gz
